# Generated by Django 2.2.7 on 2021-03-07 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('candidate_pic', models.ImageField(upload_to='pics')),
                ('candidate_code', models.CharField(max_length=100)),
                ('candidate_vote', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_title', models.CharField(max_length=400)),
                ('election_code', models.CharField(max_length=100)),
                ('election_shows', models.IntegerField(default=0)),
                ('election_show', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_ids', models.CharField(max_length=100)),
                ('vote_candidate_code', models.CharField(max_length=100)),
                ('voters_id', models.CharField(max_length=100)),
                ('vote_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting_process.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_id', models.CharField(max_length=100)),
                ('voters_id', models.CharField(max_length=100)),
                ('voters_email', models.EmailField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voters_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting_process.Election')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting_process.Election'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
