# Generated by Django 2.2.7 on 2021-03-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='election',
            name='election_start',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_vote',
            field=models.IntegerField(default=0),
        ),
    ]
