# Generated by Django 2.2.7 on 2021-03-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting_process', '0002_auto_20210313_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_start',
            field=models.DateTimeField(),
        ),
    ]
