# Generated by Django 2.2.7 on 2021-03-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting_process', '0003_auto_20210313_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_end',
            field=models.DateTimeField(),
        ),
    ]
