# Generated by Django 2.2.7 on 2021-03-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting_process', '0004_auto_20210313_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_end',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
