# Generated by Django 2.2.7 on 2021-03-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voting_process', '0005_auto_20210315_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='election_end',
            new_name='election_end_time',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='election_start',
            new_name='election_start_time',
        ),
    ]
