# Generated by Django 2.2.7 on 2021-03-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting_process', '0006_auto_20210315_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
