# Generated by Django 2.2.7 on 2021-03-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Voting_process', '0007_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Voting_process.Position'),
            preserve_default=False,
        ),
    ]
