# Generated by Django 2.2.7 on 2020-12-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='users',
        ),
    ]
