# Generated by Django 2.2.7 on 2021-03-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0003_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_us',
        ),
    ]
